version: '3.9'
services: 
  web_server:
    build: .

    volumes:
      - ./docker-logs/container1:/src/logs
    
    network_mode: host

    deploy:
      restart_policy:
        condition: on-failure
    